packages:
  - '*/src'

catalog:
  '@antfu/eslint-config': ^7.4.2
  '@eslint/config-inspector': ^1.4.2
  '@iconify/collections': ^1.0.649
  '@iconify/json': ^2.2.438
  '@slidev/cli': ^52.11.5
  '@slidev/client': ^52.11.5
  '@slidev/theme-default': ^0.25.0
  '@types/node': ^25.2.3
  '@types/prompts': ^2.4.9
  '@types/seedrandom': ^3.0.8
  chroma-js: ^3.2.0
  eslint: ^10.0.0
  eslint-plugin-format: ^1.4.0
  esno: ^4.8.0
  execa: ^9.6.1
  fast-glob: ^3.3.3
  markdown-it-magic-link: ^0.1.4
  playwright-chromium: ^1.58.2
  pnpm: ^10.29.2
  prettier-plugin-slidev: ^1.0.5
  prompts: ^2.4.2
  rimraf: ^6.1.2
  seedrandom: ^3.0.5
  slidev-addon-graph: ^1.0.0
  taze: ^19.9.2
  typescript: ^5.9.3
  unocss: ^66.6.0
  vis-data: ^8.0.3
  vis-network: ^10.0.2
  vis-timeline: ^8.5.0
  vue-router: ^5.0.2
  vue-tsc: ^3.2.4
  vue: ^3.5.28
